<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
      <!--TODO--> 
	  <LangVersion>8.0</LangVersion>
	  <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Polly" Version="8.6.5" />
    <PackageReference Include="Polly.Contrib.WaitAndRetry" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="xAPIClient">
      <HintPath>Src\Plugins\xAPIClient.dll</HintPath>
    </Reference>
    <Reference Include="xAPIModel">
      <HintPath>Src\Plugins\xAPIModel.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
